# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm install
          - npm run start 
          - pipe: atlassian/aws-code-deploy:0.2.5
            variables:
              AWS_ACCESS_KEY_ID: '$AWS_ACCESS_KEY_ID'
              AWS_SECRET_ACCESS_KEY: '$AWS_SECRET_ACCESS_KEY'
              AWS_DEFAULT_REGION: '$AWS_DEFAULT_REGION'
              APPLICATION_NAME: '$APPLICATION_NAME'
              COMMAND: 'deploy' # 'upload' or 'deploy'.

